# site
title: Geek Reader
name: Reader
url: http://geekr.js.org
githubUrl: https://github.com/ruanyl/geekr-redux
root: /

# post
postDir: _posts

# build
outputDir: dist

#cname
cname: geekr.js.org

pageSize: 15
